export const LOCATIONS: Record<string, string[]> = {
  'Angeles City': [
    'Agapito del Rosario', 'Anunas', 'Balibago', 'Capaya', 'Claro M. Recto',
    'Cuayan', 'Cutcut', 'Lourdes North West', 'Lourdes Sur', 'Malabanias',
    'Margot', 'Mining', 'Ninoy Aquino', 'Pampang', 'Pandan', 'Pulung Cacutud',
    'Pulung Maragul', 'Pulungbulo', 'Salapungan', 'San Jose', 'Santa Trinidad',
    'Santo Cristo', 'Santo Domingo', 'Santo Rosario', 'Telecom',
    'Virgen Delos Remedios',
  ],
  'San Fernando': [
    'Alasas', 'Baliti', 'Bulaon', 'Calulut', 'Del Carmen', 'Del Pilar',
    'Del Rosario', 'Dolores', 'Juliana', 'Lara', 'Lourdes', 'Magliman',
    'Maimpis', 'Malino', 'Malpitic', 'Pandaras', 'Panipuan', 'Pulung Bulu',
    'Quebiawan', 'Saguin', 'San Agustin', 'San Felipe', 'San Isidro',
    'San Jose', 'San Nicolas', 'San Pedro', 'Santa Lucia', 'Santa Teresita',
    'Santiago', 'Sindalan', 'Telabastagan',
  ],
  'Mabalacat': [
    'Atlu-Bola', 'Bical', 'Bundagul', 'Cacutud', 'Calumpang', 'Camachiles',
    'Dapdap', 'Dau', 'Dolores', 'Duquit', 'Lakandula', 'Mabiga', 'Macapagal',
    'Mamatitang', 'Mangalit', 'Marcos Village', 'Mawaque', 'Paralayunan',
    'Poblacion', 'San Francisco', 'San Joaquin', 'Santa Ines', 'Santa Maria',
    'Santo Rosario', 'Sapang Balen', 'Sapang Biabas', 'Tabun',
  ],
  'Clark': [
    'Clark Freeport Zone', 'Hadrian', 'Jose Abad Santos',
    'Leonico', 'Marcos', 'Philippine-American Friendship',
  ],
  'Apalit': [
    'Balucuc', 'Calantipe', 'Cansinala', 'Capalangan', 'Cargados', 'Lanang',
    'San Juan', 'San Vicente', 'Santa Ana', 'Sucad', 'Sulipan', 'Tabuyuc',
  ],
  'Arayat': [
    'Arenas', 'Baliti', 'Batasan', 'Buensuceso', 'Candating', 'Gatiawin',
    'Guemasan', 'La Paz', 'Lacmit', 'Lacquios', 'Mangga-Cacutud', 'Mapalad',
    'Palinlang', 'Paralaya', 'Poblacion', 'San Agustin Norte', 'San Agustin Sur',
    'San Antonio', 'San Jose Mesulo', 'San Juan Bano', 'San Mateo', 'San Nicolas',
    'San Roque Bano', 'San Roque Dau', 'Santa Lucia', 'Santo Niño', 'Suclayin',
    'Tibag', 'Vizal San Pablo', 'Vizal Santo Cristo', 'Vizal Santo Niño',
  ],
  'Bacolor': [
    'Balas', 'Cabalantian', 'Cabambangan', 'Cabetican', 'Calibutbut', 'Concepcion',
    'Dolores', 'Duat', 'Macabacle', 'Magliman', 'Maliwalu', 'Mesalipit',
    'Parulog', 'Potrero', 'San Antonio', 'San Isidro', 'San Vicente', 'Santa Barbara',
    'Santa Ines', 'Talba', 'Tinajero',
  ],
  'Candaba': [
    'Bahay Pare', 'Bambang', 'Baranday', 'Batasan Matanda', 'Bulaon', 'Burdeos',
    'Gulap', 'Lanang', 'Lourdes', 'Magumbali', 'Mandasig', 'Mandili', 'Mangga',
    'Mapaniqui', 'Paligui', 'Sampaloc', 'San Agustin', 'San Ildefonso', 'San Jose',
    'San Pedro', 'Santa Filomena', 'Santo Cristo', 'Tagulod', 'Talang',
    'Telapayong', 'Vizal San Pablo',
  ],
  'Floridablanca': [
    'Anon', 'Apalit', 'Bacong', 'Basa Air Base', 'Benedicto', 'Bodega',
    'Cabangcalan', 'Calantas', 'Carmencita', 'Consuelo', 'Dampe', 'Del Carmen',
    'Fortuna', 'Gutad', 'Mabical', 'Magalang', 'Maligaya', 'Nabuclod',
    'Pabanlag', 'Paguiruan', 'Palmayo', 'Pandaguirig', 'Poblacion', 'San Antonio',
    'San Isidro', 'San Jose', 'San Nicolas', 'San Pedro', 'San Ramon',
    'San Roque', 'Santa Monica', 'Santo Rosario', 'Solib', 'Valdez',
  ],
  'Guagua': [
    'Ascomo', 'Bancal', 'Jose Abad Santos', 'Lambac', 'Magsaysay', 'Maquiapo',
    'Mitla', 'Palanan', 'Poblacion', 'Pulungmasle', 'Rizal', 'San Agustin',
    'San Francisco', 'San Isidro', 'San Jose', 'San Juan', 'San Matias',
    'San Miguel', 'San Nicolas 1st', 'San Nicolas 2nd', 'San Pablo',
    'San Pedro Palcarangan', 'San Pedro Sasmuan', 'Santa Filomena', 'Santa Ines',
    'Santa Ursula', 'Santo Cristo',
  ],
  'Lubao': [
    'Balantacan', 'Baruya', 'Batasan Matanda', 'Buensuceso', 'Calangain',
    'Concepcion', 'Del Carmen', 'Don Ignacio Dimson', 'Lourdes', 'Prado Siongco',
    'Remedios', 'San Agustin', 'San Antonio', 'San Francisco', 'San Isidro',
    'San Jose Gumi', 'San Nicolas 1st', 'San Pablo 1st', 'San Pedro',
    'San Ramon', 'San Roque', 'Santa Barbara', 'Santa Cruz', 'Santa Catalina',
    'Santa Lucia', 'Santa Maria', 'Santo Tomas', 'Seriales', 'Sulipan',
  ],
  'Macabebe': [
    'Batasan', 'Caduang Tete', 'Candelaria', 'Castuli', 'Consuelo', 'Dalayap',
    'Macabebe Poblacion', 'Malusac', 'Saguin', 'San Esteban', 'San Francisco',
    'San Gabriel', 'San Isidro', 'San Jose', 'San Juan', 'San Nicolas',
    'San Rafael', 'Santa Cruz', 'Santa Lutgarda', 'Santa Maria', 'Santa Rita',
    'Santo Niño', 'Santo Rosario', 'Saplad David', 'Tacasan',
  ],
  'Magalang': [
    'Abacan', 'Ali Aga', 'Ayala', 'Ayala Kanluran', 'Balaiti', 'Batasan',
    'Bulaon', 'Camias', 'Dolores', 'Escaler', 'La Paz', 'Navaling', 'San Agustin',
    'San Antonio', 'San Francisco', 'San Ildefonso', 'San Isidro', 'San Jose',
    'San Miguel', 'San Nicolas 1st', 'San Nicolas 2nd', 'San Pablo',
    'San Pedro', 'San Roque', 'San Vicente', 'Santa Cruz', 'Santa Lucia',
    'Santa Maria', 'Santo Niño', 'Santo Rosario', 'Santo Tomas', 'Turu',
  ],
  'Masantol': [
    'Alauli', 'Bagang', 'Balibago', 'Bebe Anac', 'Bebe Matua', 'Bulac',
    'Cambasi', 'Malauli', 'Nigui', 'Palimpe', 'Puti', 'Sagrada Familia',
    'San Agustin Anac', 'San Agustin Matua', 'San Antonio', 'San Isidro Anac',
    'San Isidro Matua', 'San Nicolas', 'San Pedro', 'Santa Cruz Anac',
    'Santa Cruz Matua', 'Santa Lucia', 'Santa Monica', 'Santo Niño',
    'Santo Rosario Anac', 'Santo Rosario Matua', 'Sua',
  ],
  'Mexico': [
    'Acli', 'Anao', 'Balas', 'Buenavista', 'Camuning', 'Cawayan', 'Concepcion',
    'Culubasa', 'Divisoria', 'Dolores', 'Eden', 'Gandus', 'Lagundi', 'Laput',
    'Laug', 'Lazaro', 'Lourdes', 'Malino', 'Masamat', 'Masangsang', 'Nueva Victoria',
    'Pandacaqui', 'Pangatlan', 'Panipuan', 'Parian', 'Poblacion', 'Puti',
    'Sabanilla', 'San Antonio', 'San Carlos', 'San Jose', 'San Juan', 'San Lorenzo',
    'San Miguel', 'San Nicolas', 'San Pablo', 'San Patricio', 'San Rafael',
    'San Roque', 'San Vicente', 'Santa Cruz', 'Santa Maria', 'Santo Tomas',
    'Sapang Maisac', 'Suclaban', 'Tangle',
  ],
  'Minalin': [
    'Bulac', 'Dawe', 'Lourdes', 'Maniango', 'San Francisco 1st', 'San Francisco 2nd',
    'San Isidro', 'San Nicolas', 'San Pedro', 'Santa Catalina', 'Santa Maria',
    'Santa Rita', 'Santo Domingo', 'Saplad',
  ],
  'Porac': [
    'Babo Pangulo', 'Babo Sacan', 'Balubad', 'Calzadang Bayu', 'Camias',
    'Cangatba', 'Diaz', 'Dolores', 'Inararo', 'Jalung', 'Mancatian', 'Manuali',
    'Mitla Proper', 'Palat', 'Pias', 'Pio', 'Poblacion', 'Pulong Santol',
    'Sap-Ang', 'San Jose Malubago', 'San Marcos', 'San Nicholas', 'Santa Cruz',
    'Santa Cruz Nery', 'Sepung Bulaun', 'Sinubli', 'Tartaro',
  ],
  'San Luis': [
    'San Agustin', 'San Carlos', 'San Isidro', 'San Jose', 'San Juan',
    'San Nicolas', 'San Roque', 'San Sebastian', 'Santa Catalina', 'Santa Cruz',
    'Santa Lucia', 'Santa Maria', 'Santa Rita', 'Santo Niño', 'Santo Rosario',
  ],
  'San Simon': [
    'Concepcion', 'De La Paz', 'San Agustin', 'San Isidro', 'San Jose',
    'San Juan', 'San Miguel', 'San Nicolas', 'San Pablo', 'San Pedro',
    'San Roque', 'San Vicente', 'Santa Cruz', 'Santa Monica', 'Santo Niño',
  ],
  'Santa Ana': [
    'San Agustin', 'San Bartolome', 'San Isidro', 'San Jose', 'San Juan',
    'San Nicolas', 'San Pablo', 'San Pedro', 'San Roque', 'San Vicente',
    'Santa Cruz', 'Santa Lucia', 'Santo Niño',
  ],
  'Santa Rita': [
    'Becuran', 'Dau', 'San Agustin', 'San Basilio', 'San Isidro', 'San Jose',
    'San Juan', 'San Matias', 'San Nicolas', 'San Pablo Lipit', 'San Pablo Proper',
    'San Pedro Calangain', 'Santa Monica', 'Santo Cristo', 'Silab',
  ],
  'Santo Tomas': [
    'Moras De La Paz', 'Poblacion', 'San Bartolome', 'San Matias', 'San Vicente',
    'Santo Rosario', 'Santo Tomas Propio',
  ],
  'Sasmuan': [
    'Batang 1st', 'Batang 2nd', 'Mabuanbuan', 'Malusac', 'Sasmuan Pob.',
    'San Nicolas 1st', 'San Nicolas 2nd', 'San Pedro', 'Santa Lucia', 'Santo Tomas',
  ],
};

export const CITY_COORDS: Record<string, { lat: number; lng: number }> = {
  'Angeles City':  { lat: 15.1450, lng: 120.5887 },
  'San Fernando':  { lat: 15.0289, lng: 120.6898 },
  'Mabalacat':     { lat: 15.2167, lng: 120.5833 },
  'Clark':         { lat: 15.1860, lng: 120.5540 },
  'Apalit':        { lat: 14.9528, lng: 120.7597 },
  'Arayat':        { lat: 15.1478, lng: 120.7706 },
  'Bacolor':       { lat: 15.0567, lng: 120.6531 },
  'Candaba':       { lat: 15.0936, lng: 120.8278 },
  'Floridablanca': { lat: 14.9997, lng: 120.5019 },
  'Guagua':        { lat: 14.9736, lng: 120.6367 },
  'Lubao':         { lat: 14.9303, lng: 120.6017 },
  'Macabebe':      { lat: 14.9078, lng: 120.7150 },
  'Magalang':      { lat: 15.2147, lng: 120.6625 },
  'Masantol':      { lat: 14.8958, lng: 120.7283 },
  'Mexico':        { lat: 15.0681, lng: 120.7197 },
  'Minalin':       { lat: 14.9678, lng: 120.7003 },
  'Porac':         { lat: 15.0736, lng: 120.5381 },
  'San Luis':      { lat: 15.0367, lng: 120.7897 },
  'San Simon':     { lat: 14.9978, lng: 120.7756 },
  'Santa Ana':     { lat: 15.0897, lng: 120.7681 },
  'Santa Rita':    { lat: 15.0078, lng: 120.6467 },
  'Santo Tomas':   { lat: 15.0547, lng: 120.6767 },
  'Sasmuan':       { lat: 14.9303, lng: 120.6753 },
};